### PR TITLE
Load routes

### PR DESCRIPTION
**Pull request by Larsklopstra**
This enables loading route files from the `routes` directory

### CODE REVIEW

**Comment by fallback** [comment]
That's funny: yesterday I've added that feature to local fork of the package! Not pushed and PRed though. Nice to see that I'm not the only who needed that feature.

**Comment by freekmurze** [comment]
Could you add a new section about this in the readme? Thanks!

**Comment by Larsklopstra** [comment]
Here we go @freekmurze

**Comment by freekmurze** [comment]
Thanks! I'll polish this a bit and release it!

**Comment by Larsklopstra** [comment]
Great, thanks!

**Pull request merged**
